import { Metadata } from "next";
import Sidebar from "./_components/Sidebar";
import { UserLogged } from "./_components/UserLogged";

export const metadata: Metadata = {
  title: "Portly | Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex gap-3">
      <Sidebar />
      <UserLogged />
      <div className="bg-[#111111] rounded-2xl m-3 px-3 py-3 w-full">
        {children}
      </div>

    </div>
  );
}
